
import { User, Flight, FlightResult } from '../types';

export const INITIAL_FLIGHTS: Flight[] = [
  {
    id: 'f1',
    flightNumber: 'FC-101',
    origin: 'New York (JFK)',
    destination: 'London (LHR)',
    departureTime: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString(), // 2 days from now
    arrivalTime: new Date(new Date().setDate(new Date().getDate() + 2) + 7 * 60 * 60 * 1000).toISOString(),
    gate: 'B12',
    seat: '4A',
    class: 'Business',
    status: 'On Time',
    aircraft: 'Boeing 787-9',
    alerts: {
      priceChange: false,
      statusUpdate: true
    }
  },
  {
    id: 'f2',
    flightNumber: 'FC-404',
    origin: 'London (LHR)',
    destination: 'Tokyo (HND)',
    departureTime: new Date(new Date().setDate(new Date().getDate() + 10)).toISOString(),
    arrivalTime: new Date(new Date().setDate(new Date().getDate() + 10) + 14 * 60 * 60 * 1000).toISOString(),
    gate: 'A05',
    seat: '12F',
    class: 'Economy',
    status: 'Delayed',
    aircraft: 'Airbus A350-1000',
    alerts: {
      priceChange: true,
      statusUpdate: true
    }
  }
];

export const MOCK_SEARCH_RESULTS: FlightResult[] = [
  // JFK -> LHR
  {
    id: 'sr1',
    airline: 'Flopcoast Airways',
    flightNumber: 'FC-101',
    origin: 'New York (JFK)',
    destination: 'London (LHR)',
    departureTime: '08:00',
    arrivalTime: '20:00',
    duration: '7h 00m',
    stops: 0,
    price: 450,
    aircraft: 'Boeing 787-9',
    baggage: '2x 23kg Checked',
    amenities: ['WiFi', 'Meals', 'USB Power', 'On-demand TV'],
    cabinClass: 'Economy',
    priceTrend: 'stable'
  },
  {
    id: 'sr2',
    airline: 'Flopcoast Airways',
    flightNumber: 'FC-105',
    origin: 'New York (JFK)',
    destination: 'London (LHR)',
    departureTime: '18:30',
    arrivalTime: '06:30',
    duration: '7h 00m',
    stops: 0,
    price: 1250,
    aircraft: 'Boeing 777-300ER',
    baggage: '2x 32kg Checked',
    amenities: ['Meals', 'USB Power', 'On-demand TV', 'Lounge Access'],
    cabinClass: 'Premium Economy',
    priceTrend: 'up'
  },
  {
    id: 'sr3',
    airline: 'Flopcoast Connect',
    flightNumber: 'FC-220',
    origin: 'New York (JFK)',
    destination: 'London (LHR)',
    departureTime: '12:00',
    arrivalTime: '02:00',
    duration: '9h 00m',
    stops: 1,
    price: 380,
    aircraft: 'Airbus A321XLR',
    baggage: 'Cabin Bag Only',
    amenities: ['USB Power', 'Stream to Device'],
    cabinClass: 'Economy',
    priceTrend: 'down',
    layoverDuration: '1h 45m'
  },
  // LAX -> SYD
  {
    id: 'sr6',
    airline: 'Flopcoast Pacific',
    flightNumber: 'FC-888',
    origin: 'Los Angeles (LAX)',
    destination: 'Sydney (SYD)',
    departureTime: '22:30',
    arrivalTime: '06:30',
    duration: '15h 00m',
    stops: 0,
    price: 1200,
    aircraft: 'Boeing 787-9',
    baggage: '2x 23kg Checked',
    amenities: ['WiFi', 'Meals', 'Snacks', 'Sleep Kit'],
    cabinClass: 'Economy',
    priceTrend: 'up'
  },
  // SIN -> HND
  {
    id: 'sr7',
    airline: 'Flopcoast Asia',
    flightNumber: 'FC-772',
    origin: 'Singapore (SIN)',
    destination: 'Tokyo (HND)',
    departureTime: '09:00',
    arrivalTime: '17:00',
    duration: '7h 00m',
    stops: 0,
    price: 480,
    aircraft: 'Boeing 787-10',
    baggage: '1x 30kg Checked',
    amenities: ['WiFi', 'Asian Meal Options', 'Power'],
    cabinClass: 'Economy',
    priceTrend: 'stable'
  },
  // South American Routes
  {
    id: 'sr9',
    airline: 'Flopcoast Americas',
    flightNumber: 'FC-901',
    origin: 'New York (JFK)',
    destination: 'Sao Paulo (GRU)',
    departureTime: '21:00',
    arrivalTime: '08:00',
    duration: '10h 00m',
    stops: 0,
    price: 850,
    aircraft: 'Boeing 777-200LR',
    baggage: '2x 32kg Checked',
    amenities: ['WiFi', 'Hot Meals', 'Pillow/Blanket'],
    cabinClass: 'Economy',
    priceTrend: 'down'
  },
  // NEW: Seoul (ICN) -> Bangkok (BKK)
  {
    id: 'sr20',
    airline: 'Flopcoast Asia',
    flightNumber: 'FC-333',
    origin: 'Seoul (ICN)',
    destination: 'Bangkok (BKK)',
    departureTime: '10:30',
    arrivalTime: '14:30',
    duration: '6h 00m',
    stops: 0,
    price: 350,
    aircraft: 'Airbus A330-300',
    baggage: '1x 25kg Checked',
    amenities: ['WiFi', 'Meal', 'Entertainment'],
    cabinClass: 'Economy',
    priceTrend: 'stable'
  },
  // NEW: Santiago (SCL) -> Lima (LIM)
  {
    id: 'sr21',
    airline: 'Flopcoast Americas',
    flightNumber: 'FC-444',
    origin: 'Santiago (SCL)',
    destination: 'Lima (LIM)',
    departureTime: '13:00',
    arrivalTime: '16:00',
    duration: '4h 00m',
    stops: 0,
    price: 220,
    aircraft: 'Airbus A320neo',
    baggage: '1x 23kg Checked',
    amenities: ['USB Power', 'Snack'],
    cabinClass: 'Economy',
    priceTrend: 'up'
  },
  // NEW: Lima (LIM) -> Los Angeles (LAX)
  {
    id: 'sr22',
    airline: 'Flopcoast Americas',
    flightNumber: 'FC-555',
    origin: 'Lima (LIM)',
    destination: 'Los Angeles (LAX)',
    departureTime: '01:00',
    arrivalTime: '08:00',
    duration: '9h 00m',
    stops: 0,
    price: 600,
    aircraft: 'Boeing 787-8',
    baggage: '2x 23kg Checked',
    amenities: ['WiFi', 'Full Meal', 'Blanket'],
    cabinClass: 'Economy',
    priceTrend: 'down'
  },
  
  // --- EXISTING FICTIONAL ROUTES ---
  // Floptopia (FLP) <-> Queen Jiafei (JLU)
  {
    id: 'sr12',
    airline: 'Flopcoast Airways',
    flightNumber: 'FC-666',
    origin: 'Floptopia (FLP)',
    destination: 'Queen Jiafei (JLU)',
    departureTime: '10:00',
    arrivalTime: '13:30',
    duration: '3h 30m',
    stops: 0,
    price: 320,
    aircraft: 'Airbus A320neo',
    baggage: '1x 23kg Checked',
    amenities: ['WiFi', 'Snacks', 'USB Power'],
    cabinClass: 'Economy',
    priceTrend: 'stable'
  },
  // Manipple (MAY) <-> Alejandra Coast (AJC)
  {
    id: 'sr13',
    airline: 'Flopcoast Airways',
    flightNumber: 'FC-111',
    origin: 'Manipple (MAY)',
    destination: 'Alejandra Coast (AJC)',
    departureTime: '14:00',
    arrivalTime: '16:00',
    duration: '2h 00m',
    stops: 0,
    price: 180,
    aircraft: 'Boeing 737-800',
    baggage: 'Cabin Bag Only',
    amenities: ['USB Power', 'Beverage Service'],
    cabinClass: 'Economy',
    priceTrend: 'up'
  },
   // Erendits (ERD) <-> Jilu City (JLC)
   {
    id: 'sr14',
    airline: 'Flopcoast Airways',
    flightNumber: 'FC-789',
    origin: 'Erendits (ERD)',
    destination: 'Jilu City (JLC)',
    departureTime: '08:45',
    arrivalTime: '10:15',
    duration: '1h 30m',
    stops: 0,
    price: 150,
    aircraft: 'Embraer E190',
    baggage: '1x 23kg Checked',
    amenities: ['No WiFi', 'Snacks'],
    cabinClass: 'Economy',
    priceTrend: 'down'
  },
  // Poosay Bottom (PBT) <-> Summeria (XSX)
  {
    id: 'sr15',
    airline: 'Flopcoast Express',
    flightNumber: 'FC-001',
    origin: 'Poosay Bottom (PBT)',
    destination: 'Summeria (XSX)',
    departureTime: '16:20',
    arrivalTime: '19:40',
    duration: '3h 20m',
    stops: 0,
    price: 290,
    aircraft: 'Airbus A220',
    baggage: '1x 23kg Checked',
    amenities: ['WiFi', 'Power', 'Drinks'],
    cabinClass: 'Economy',
    priceTrend: 'stable'
  },
  // Da Hood (DHR) <-> New York (JFK)
  {
    id: 'sr16',
    airline: 'Flopcoast Airways',
    flightNumber: 'FC-420',
    origin: 'Da Hood (DHR)',
    destination: 'New York (JFK)',
    departureTime: '23:00',
    arrivalTime: '05:00',
    duration: '6h 00m',
    stops: 0,
    price: 400,
    aircraft: 'Boeing 757-200',
    baggage: '2x 23kg Checked',
    amenities: ['WiFi', 'Full Meal'],
    cabinClass: 'Economy',
    priceTrend: 'up'
  },
  // Queen Jiafei (JLU) -> Floptopia (FLP) - Premium
  {
    id: 'sr17',
    airline: 'Flopcoast Airways',
    flightNumber: 'FC-667',
    origin: 'Queen Jiafei (JLU)',
    destination: 'Floptopia (FLP)',
    departureTime: '18:00',
    arrivalTime: '21:30',
    duration: '3h 30m',
    stops: 0,
    price: 850,
    aircraft: 'Airbus A320neo',
    baggage: '2x 32kg Checked',
    amenities: ['WiFi', 'Gourmet Meal', 'Priority Boarding'],
    cabinClass: 'Business',
    priceTrend: 'stable'
  },
  // NEW ASIAN ROUTES
  {
    id: 'sr25',
    airline: 'Flopcoast Asia',
    flightNumber: 'FC-808',
    origin: 'Tokyo (HND)',
    destination: 'Beijing (PEK)',
    departureTime: '14:00',
    arrivalTime: '17:00',
    duration: '4h 00m',
    stops: 0,
    price: 320,
    aircraft: 'Boeing 787-8',
    baggage: '1x 23kg Checked',
    amenities: ['WiFi', 'Meal'],
    cabinClass: 'Economy',
    priceTrend: 'down'
  },
  {
    id: 'sr26',
    airline: 'Flopcoast Asia',
    flightNumber: 'FC-809',
    origin: 'Singapore (SIN)',
    destination: 'Mumbai (BOM)',
    departureTime: '18:30',
    arrivalTime: '21:30',
    duration: '5h 30m',
    stops: 0,
    price: 410,
    aircraft: 'Airbus A350-900',
    baggage: '2x 23kg Checked',
    amenities: ['WiFi', 'Indian Meal Options', 'Power'],
    cabinClass: 'Economy',
    priceTrend: 'stable'
  },
  {
    id: 'sr27',
    airline: 'Flopcoast Airways',
    flightNumber: 'FC-810',
    origin: 'Hong Kong (HKG)',
    destination: 'London (LHR)',
    departureTime: '23:00',
    arrivalTime: '05:00',
    duration: '13h 00m',
    stops: 0,
    price: 890,
    aircraft: 'Boeing 777-300ER',
    baggage: '2x 23kg Checked',
    amenities: ['WiFi', 'Full Meal Service', 'Entertainment'],
    cabinClass: 'Economy',
    priceTrend: 'up'
  },
  {
    id: 'sr28',
    airline: 'Flopcoast Asia',
    flightNumber: 'FC-811',
    origin: 'Shanghai (PVG)',
    destination: 'Tokyo (HND)',
    departureTime: '09:00',
    arrivalTime: '13:00',
    duration: '3h 00m',
    stops: 0,
    price: 280,
    aircraft: 'Airbus A330-300',
    baggage: '1x 23kg Checked',
    amenities: ['Snack', 'USB Power'],
    cabinClass: 'Economy',
    priceTrend: 'stable'
  },
  // NEW SOUTH AMERICAN ROUTES
  {
    id: 'sr30',
    airline: 'Flopcoast Americas',
    flightNumber: 'FC-950',
    origin: 'Sao Paulo (GRU)',
    destination: 'Rio de Janeiro (GIG)',
    departureTime: '07:00',
    arrivalTime: '08:00',
    duration: '1h 00m',
    stops: 0,
    price: 120,
    aircraft: 'Embraer E195-E2',
    baggage: '1x 23kg Checked',
    amenities: ['Snack'],
    cabinClass: 'Economy',
    priceTrend: 'stable'
  },
  {
    id: 'sr31',
    airline: 'Flopcoast Americas',
    flightNumber: 'FC-951',
    origin: 'Lima (LIM)',
    destination: 'Cusco (CUZ)',
    departureTime: '06:00',
    arrivalTime: '07:20',
    duration: '1h 20m',
    stops: 0,
    price: 150,
    aircraft: 'Airbus A319',
    baggage: '1x 23kg Checked',
    amenities: ['Beverage'],
    cabinClass: 'Economy',
    priceTrend: 'up'
  },
  
  // --- NEW: AFRICA ROUTES ---
  {
    id: 'sr40',
    airline: 'Flopcoast Africa',
    flightNumber: 'FC-1001',
    origin: 'London (LHR)',
    destination: 'Johannesburg (JNB)',
    departureTime: '19:00',
    arrivalTime: '07:00',
    duration: '11h 00m',
    stops: 0,
    price: 950,
    aircraft: 'Airbus A380-800',
    baggage: '2x 23kg Checked',
    amenities: ['WiFi', 'Full Meals', 'Entertainment'],
    cabinClass: 'Economy',
    priceTrend: 'down'
  },
  {
    id: 'sr41',
    airline: 'Flopcoast Africa',
    flightNumber: 'FC-1005',
    origin: 'Cairo (CAI)',
    destination: 'Dubai (DXB)',
    departureTime: '14:00',
    arrivalTime: '19:30',
    duration: '3h 30m',
    stops: 0,
    price: 320,
    aircraft: 'Boeing 737 MAX 8',
    baggage: '1x 23kg Checked',
    amenities: ['WiFi', 'Meal'],
    cabinClass: 'Economy',
    priceTrend: 'stable'
  },
  {
    id: 'sr42',
    airline: 'Flopcoast Africa',
    flightNumber: 'FC-1010',
    origin: 'Lagos (LOS)',
    destination: 'London (LHR)',
    departureTime: '22:45',
    arrivalTime: '05:15',
    duration: '6h 30m',
    stops: 0,
    price: 780,
    aircraft: 'Boeing 787-9',
    baggage: '2x 32kg Checked',
    amenities: ['WiFi', 'Dinner', 'Breakfast'],
    cabinClass: 'Business',
    priceTrend: 'up'
  },

  // --- NEW: EUROPE ROUTES ---
  {
    id: 'sr50',
    airline: 'Flopcoast Europe',
    flightNumber: 'FC-2020',
    origin: 'Paris (CDG)',
    destination: 'New York (JFK)',
    departureTime: '13:00',
    arrivalTime: '15:30',
    duration: '8h 30m',
    stops: 0,
    price: 540,
    aircraft: 'Airbus A350-900',
    baggage: '1x 23kg Checked',
    amenities: ['WiFi', 'French Cuisine', 'Wine'],
    cabinClass: 'Economy',
    priceTrend: 'stable'
  },
  {
    id: 'sr51',
    airline: 'Flopcoast Europe',
    flightNumber: 'FC-2030',
    origin: 'Berlin (BER)',
    destination: 'London (LHR)',
    departureTime: '08:00',
    arrivalTime: '09:00',
    duration: '2h 00m',
    stops: 0,
    price: 120,
    aircraft: 'Airbus A320',
    baggage: 'Cabin Bag Only',
    amenities: ['Snack'],
    cabinClass: 'Economy',
    priceTrend: 'down'
  },
  {
    id: 'sr52',
    airline: 'Flopcoast Europe',
    flightNumber: 'FC-2040',
    origin: 'Rome (FCO)',
    destination: 'New York (JFK)',
    departureTime: '11:00',
    arrivalTime: '14:30',
    duration: '9h 30m',
    stops: 0,
    price: 600,
    aircraft: 'Boeing 777-200',
    baggage: '2x 23kg Checked',
    amenities: ['WiFi', 'Italian Meals'],
    cabinClass: 'Economy',
    priceTrend: 'up'
  },
  {
    id: 'sr53',
    airline: 'Flopcoast Europe',
    flightNumber: 'FC-2050',
    origin: 'Madrid (MAD)',
    destination: 'Bogota (BOG)',
    departureTime: '16:00',
    arrivalTime: '20:30',
    duration: '10h 30m',
    stops: 0,
    price: 720,
    aircraft: 'Boeing 787-8',
    baggage: '2x 23kg Checked',
    amenities: ['WiFi', 'Meals', 'Entertainment'],
    cabinClass: 'Economy',
    priceTrend: 'stable'
  },

  // --- NEW: NORTH AMERICA ROUTES ---
  {
    id: 'sr60',
    airline: 'Flopcoast Americas',
    flightNumber: 'FC-3001',
    origin: 'Toronto (YYZ)',
    destination: 'London (LHR)',
    departureTime: '19:30',
    arrivalTime: '07:30',
    duration: '7h 00m',
    stops: 0,
    price: 580,
    aircraft: 'Boeing 787-9',
    baggage: '1x 23kg Checked',
    amenities: ['WiFi', 'Meal', 'USB Power'],
    cabinClass: 'Economy',
    priceTrend: 'down'
  },
  {
    id: 'sr61',
    airline: 'Flopcoast Americas',
    flightNumber: 'FC-3010',
    origin: 'Mexico City (MEX)',
    destination: 'Los Angeles (LAX)',
    departureTime: '09:00',
    arrivalTime: '11:00',
    duration: '4h 00m',
    stops: 0,
    price: 250,
    aircraft: 'Boeing 737 MAX 8',
    baggage: '1x 23kg Checked',
    amenities: ['Snack', 'WiFi'],
    cabinClass: 'Economy',
    priceTrend: 'stable'
  },
  {
    id: 'sr62',
    airline: 'Flopcoast Americas',
    flightNumber: 'FC-3020',
    origin: 'Chicago (ORD)',
    destination: 'London (LHR)',
    departureTime: '17:00',
    arrivalTime: '06:00',
    duration: '8h 00m',
    stops: 0,
    price: 620,
    aircraft: 'Boeing 767-300',
    baggage: '1x 23kg Checked',
    amenities: ['Meal', 'WiFi'],
    cabinClass: 'Economy',
    priceTrend: 'up'
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'u1',
    name: 'Admin User',
    email: 'admin@flopcoast.com',
    role: 'ADMIN',
    awardsTier: 'Ultimate',
    awardsPoints: 150000,
    upcomingFlights: [] 
  },
  {
    id: 'u2',
    name: 'Demo Traveler',
    email: 'demo@flopcoast.com',
    role: 'USER',
    awardsTier: 'Gold',
    awardsPoints: 45200,
    upcomingFlights: INITIAL_FLIGHTS
  }
];
